development:
  adapter: postgresql
  encoding: unicode
  database: howyoudoin_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: howyoudoin_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: howyoudoin_production
  pool: 25
  username: 
  password:
